# All in FLU frame, meters

leader1/target:
  x: 0.0
  y: 0.0
  z: 0.0

leader2/target:
  x: 0.0
  y: -50.0
  z: 0.0

follower/target:
  x: -25.0
  y: -25.0
  z: 0.0

follower1/target:
  x: -15.0
  y: -5.0
  z: 0.0

follower2/target:
  x: -22.36
  y: -13.82
  z: 0.0

follower3/target:
  x: -22.36
  y: -36.18
  z: 0.0

follower4/target:
  x: -15.0
  y: -45.0
  z: 0.0