/**/mqtt_client:
  ros__parameters:
    broker:
      host: '1a9ad048190548b89a225a4175e78661.s1.eu.hivemq.cloud'
      port: 8883
      user: 'ground_control1'
      pass: 'Do_your_thing4'
    bridge:
      mqtt2ros:
        mqtt_topics: 
          - 'waraps/unit/surface/real/MiniUSV1/sensor/position'
          - 'waraps/unit/surface/real/MiniUSV1/sensor/heading'
        waraps/unit/surface/real/MiniUSV1/sensor/position:
          ros_topic: 'core/gps'
          ros_type: 'sensor_msgs/msg/NavSatFix'
        waraps/unit/surface/real/MiniUSV1/sensor/heading:
          ros_topic: 'core/heading'
          ros_type: 'std_msgs/msg/Float32'