/**/mqtt_client:
  ros__parameters:
    broker:
      host: '1a9ad048190548b89a225a4175e78661.s1.eu.hivemq.cloud'
      port: 8883
      user: 'ground_control1'
      pass: 'Do_your_thing4'
      tls:
        enabled: true
    bridge:
      mqtt2ros:
        mqtt_topics: 
          - 'waraps/unit/surface/real/MiniUSV1/sensor/position'
          - 'waraps/unit/surface/real/MiniUSV1/sensor/heading'
        waraps/unit/surface/real/MiniUSV1/sensor/position:
          ros_topic: '/agent0/json/gps'
          primitive: true
        waraps/unit/surface/real/MiniUSV1/sensor/heading:
          ros_topic: '/agent0/json/heading'
          primitive: true